=== ashrinkc/GiftCardStore/catalog_20048837.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- This specifies that the schema's elements and data types are from the http://www.w3.org/2001/XMLSchema namespace.
It also defines that elements and data types from the http://www.w3.org/2001/XMLSchema namespace should have an xs prefix.-->
  <xs:element name="STORE">
    <xs:complexType> <!-- complex type is used as it contains other elements and attributes-->
      <xs:sequence>
        <xs:element name="storeDetails">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="storeTitle">
                <xs:complexType>
                  <xs:sequence> <!--The sequence element determines the order in which the child elements must appear.-->
                    <xs:element name="store_name" type="xs:string"/>
                    <xs:element name="logo"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="storeDetail">
                <xs:complexType>
                  <xs:sequence> <!--The sequence element determines the order in which the child elements must appear.-->
                    <xs:element name="store_address" type="xs:string"/>
                    <xs:element name="telephoneNumber" type="xs:string"/>
                    <xs:element name="store_websiteAddress" type="xs:string"/>
                    <xs:element name="store_email">
                      <xs:simpleType> 
                        <xs:restriction base="xs:string"> 
                            <xs:pattern value="[^@]+@[^\.]+\..+"/>  <!--pattern constraint for email-->
                        </xs:restriction> 
                      </xs:simpleType> 
                    </xs:element>
                    <xs:element name="notes" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Giftcard">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="digital">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Card">
                      <xs:complexType> <!-- complex type is used as it contains other elements and attributes-->
                        <xs:sequence>
                          <xs:element name="name">
                            <xs:complexType>
                              <xs:simpleContent> <!--Only attributes and text content are allowed in the elements content type.-->
                                <xs:extension base="xs:string">  <!--declaring a type that extends MainParameter type.-->
                                  <xs:attribute name="type" use="required">
                                    <xs:simpleType>
                                      <xs:restriction base="xs:string">  <!--restricting to select only digital or physical-->
                                        <xs:enumeration value="digital"/>
                                        <xs:enumeration value="physical"/>
                                      </xs:restriction>
                                    </xs:simpleType>
                                  </xs:attribute>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="from" type="xs:string"/>
                          <xs:element name="type">
                            <xs:complexType>
                              <xs:simpleContent> <!--Only attributes and text content are allowed in the elements content type.-->
                                <xs:extension base="xs:string">
                                  <xs:attribute name="codenumber" type="xs:string" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="cost" type="xs:string"/>
                          <xs:element name="balance" type="xs:string"/>
                          <xs:element name="redeemCode">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="codeOf" type="xs:string" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="validity">
                            <xs:complexType> <!-- complex type is used as it contains other elements and attributes-->
                              <xs:sequence>
                                <xs:element name="manufactured_date" type="xs:string"/>
                                <xs:element name="expiry_date" type="xs:string"/>
                              </xs:sequence>
                              <xs:attribute name="cardUsability">
                                <xs:simpleType>
                                  <xs:restriction base="xs:string">
				 		 	 	 	 	                <xs:enumeration value="1 year"/>
                                    <xs:enumeration value="2 year"/>
                                    <xs:enumeration value="3 year"/>
				 		 	    	              </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="number_of_users" type="xs:integer"/>
                          <xs:element name="discount_vouchers">
                            <xs:complexType>
                              <xs:sequence> <!--The sequence element determines the order in which the child elements must appear.-->
                                <xs:element name="number_of_vouchers" type="xs:integer"/>
                                <xs:element name="discounted_percentage" type="xs:string"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="rating">
                            <xs:complexType>
                              <xs:simpleContent> <!--Only attributes and text content are allowed in the elements content type.-->
                                <xs:extension base="xs:decimal">
                                  <xs:attribute name="maxRating" use="required">
                                    <xs:simpleType>
                                      <xs:restriction base="xs:integer">
				 		 	 	 	 	                    <xs:minInclusive value="1"/> <!--restriction so that min value cannot be less that 1-->
                                        <xs:maxInclusive value="5"/> <!--restriction so that max value cannot be more that 5-->
				 		 	    	                  </xs:restriction>
                                    </xs:simpleType>
                                  </xs:attribute>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="desc" type="xs:string"/>
                          <xs:element name="websiteAddress" type="xs:string"/>
                          <xs:element name="email">
                            <xs:simpleType> <!--Only attributes and text content are allowed in the elements content type.-->
                              <xs:restriction base="xs:string"> 
                                <xs:pattern value="[^@]+@[^\.]+\..+"/> <!--pattern constraint for email-->
                              </xs:restriction> 
                            </xs:simpleType> 
                          </xs:element>
                          <xs:element minOccurs="0" name="available_for" type="xs:string"/>
                          <xs:element name="quantity" type="xs:integer"/>
                          <xs:element minOccurs="0" name="refundable_within" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="giftOf" type="xs:string" fixed="sto1"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element maxOccurs="unbounded" name="physical">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Card">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name">
                            <xs:complexType>
                              <xs:simpleContent> <!--Only attributes and text content are allowed in the elements content type.-->
                                <xs:extension base="xs:string"> <!--declaring a type that extends MainParameter type.-->
                                  <xs:attribute name="type" type="xs:string" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="from" type="xs:string"/>
                          <xs:element name="type">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                  <xs:enumeration value="Digital"/>
                                  <xs:enumeration value="Physical"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="cost" type="xs:string"/>
                          <xs:element name="balance" type="xs:string"/>
                          <xs:element name="validity">
                            <xs:complexType> <!-- complex type is used as it contains other elements and attributes-->
                              <xs:sequence>
                                <xs:element name="manufactured_date" type="xs:string"/>
                                <xs:element name="expiry_date" type="xs:string"/>
                              </xs:sequence>
                              <xs:attribute name="cardUsability" type="xs:string" use="required"/>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="number_of_users" type="xs:integer"/>
                          <xs:element name="discount_vouchers">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="number_of_vouchers" type="xs:integer"/>
                                <xs:element name="discounted_percentage" type="xs:string"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" name="color" type="xs:string"/>
                          <xs:element minOccurs="0" name="customize">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="design" type="xs:string"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="rating">
                            <xs:complexType> <!-- complex type is used as it contains other elements and attributes-->
                              <xs:simpleContent>
                                <xs:extension base="xs:decimal">  <!--declaring a type that extends MainParameter type.-->
                                  <xs:attribute name="maxRating" type="xs:integer" use="optional" default="5"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="desc" type="xs:string"/>
                          <xs:element name="websiteAddress" type="xs:string"/>
                          <xs:element name="email" type="xs:string"/>
                          <xs:element minOccurs="0" name="payment_type" type="xs:string"/>
                          <xs:element name="quantity" type="xs:integer"/>
                          <xs:element minOccurs="0" name="refundable_within" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="giftOf" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="storeID" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema> <!--end of the schema-->

=== ashrinkc/GiftCardStore/catalog_20048837.xml
<?xml  version="1.0" encoding="UTF-8" standalone="no"?>
<!--Linking css to my xml-->
<?xml-stylesheet type="text/css" href="catalog_20048837.css"?>
<!--Refrencing xml schema-->
<STORE storeID="sto1" xsi:noNamespaceSchemaLocation="catalog_20048837.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <storeDetails>
        <storeTitle>
            <store_name>Ashrin Gift Store</store_name> <!--name of the store-->
            <logo/>
        </storeTitle>
        <storeDetail>
            <store_address>
                UK, London
            </store_address> <!--address of the store-->
            <telephoneNumber>(+44 20) 555-1812</telephoneNumber> <!--number of the store-->
            <store_websiteAddress>http://www.ashringiftstore.com</store_websiteAddress>
            <store_email>dio@nhs.net</store_email> <!--email of the store-->
            <notes> <!--about the store-->
            <![CDATA[
            Ashrin gift store in London, United Kingdom sells digital gift cards. A gift card is
            a form of payment that can be used to make purchases at retail stores, gas stations,
            restaurants and other locations.
            ]]>
            </notes>
        </storeDetail>
    </storeDetails>

        <Giftcard>
        <!--15 different cards including both physical and digital are present inside giftcard-->
                <digital>
                    <Card id="a1" giftOf="sto1">
                        <name type="digital">Chipotle gift card</name> <!--name of the gift card-->
                        <from>Chiptole</from> <!--from whom the card is-->
                        <type codenumber="0PO12L">Digital</type> <!--type of card-->
                        <cost>$50.95</cost>
                        <balance>$150</balance> <!--balance of the card-->
                        <redeemCode codeOf="a1">0PO12L</redeemCode>
                        <validity cardUsability="2 year">
                            <manufactured_date>1/1/2020</manufactured_date>
                            <expiry_date>1/1/2022</expiry_date>
                        </validity> <!--valid date of the card-->
                        <number_of_users>5</number_of_users>
                        <discount_vouchers>
                            <number_of_vouchers>1</number_of_vouchers>
                            <discounted_percentage>25%</discounted_percentage>
                        </discount_vouchers>
                        <rating maxRating="5">3.5</rating>
                        <desc>
                            Give Chipotle Gift Cards to friends to treat them to delightful Mexican-themed
                            food that comes from farms, not factories.
                        </desc>
                        <websiteAddress>http://www.chipotle.com</websiteAddress>
                        <email>chi@nhs.net</email>
                        <available_for>Full payment &amp; Half payment</available_for>  <!--card availibility type-->
                        <quantity>3</quantity>
                    </Card>
                </digital>

                <digital>
                    <Card id="a2" giftOf="sto1">
                        <name type="digital">iTunes gift card</name> <!--name of the gift card-->
                        <from>Apple</from> <!--from whom the card is-->
                        <type codenumber="0P1kO">Digital</type> <!--type of card-->
                        <cost>$40</cost>
                        <balance>$100</balance> <!--balance of the card-->
                        <redeemCode codeOf="a2">0P1kO</redeemCode>
                        <validity cardUsability="2 year">
                            <manufactured_date>10/11/2020</manufactured_date>
                            <expiry_date>10/11/2022</expiry_date>
                        </validity>
                        <number_of_users>2</number_of_users>
                        <discount_vouchers>
                            <number_of_vouchers>1</number_of_vouchers>
                            <discounted_percentage>20%</discounted_percentage>
                        </discount_vouchers>
                        <rating maxRating="5">3</rating>
                        <desc>
                            Apple Gift Cards are solely for the purchase of goods and services
                            from the Apple Store or other apple services.
                        </desc>
                        <websiteAddress>http://www.itunes.com</websiteAddress>
                        <email>app@nhs.net</email>
                        <quantity>2</quantity>
                        <refundable_within>2 month</refundable_within>  <!--refundability time-->
                    </Card>
                </digital>

                <digital>
                    <Card id="a3" giftOf="sto1">
                        <name type="digital">Starbucks gift card</name> <!--name of the gift card-->
                        <from>Starbucks</from> <!--from whom the card is-->
                        <type codenumber="11PLNG">Digital</type> <!--type of card-->
                        <cost>$40</cost>
                        <balance>$130</balance> <!--balance of the card-->
                        <redeemCode codeOf="a3">11PLNG</redeemCode>
                        <validity cardUsability="1 year">
                            <manufactured_date>9/12/2020</manufactured_date>
                            <expiry_date>9/12/2021</expiry_date>
                        </validity>
                        <number_of_users>3</number_of_users>
                        <discount_vouchers>
                            <number_of_vouchers>1</number_of_vouchers>
                            <discounted_percentage>20%</discounted_percentage>
                        </discount_vouchers>
                        <rating maxRating="5">4.5</rating> <!--rating of the card-->
                        <desc>
                            Give a Starbucks Card to show appreciation towards your customers, clients and team members.
                        </desc>
                        <websiteAddress>http://www.starbucks.com</websiteAddress>
                        <email>starbuck@nhs.net</email>
                        <available_for>Full payment &amp; Half payment</available_for> 
                        <quantity>3</quantity>
                    </Card>
                </digital>

                <digital>
                    <Card id="a4" giftOf="sto1">
                        <name type="digital">Target gift card</name> <!--name of the gift card-->
                        <from>Target</from> <!--from whom the card is-->
                        <type codenumber="00P00N">Digital</type> <!--type of card-->
                        <cost>$50.95</cost>
                        <balance>$140</balance> <!--balance of the card-->
                        <redeemCode codeOf="a4">00P00N</redeemCode>
                        <validity cardUsability="3 year">
                            <manufactured_date>5/3/2020</manufactured_date>
                            <expiry_date>5/3/2023</expiry_date>
                        </validity>
                        <number_of_users>5</number_of_users>
                        <discount_vouchers>
                            <number_of_vouchers>1</number_of_vouchers>
                            <discounted_percentage>25%</discounted_percentage>
                        </discount_vouchers>
                        <rating maxRating="5">3.5</rating>
                         <desc>
                            Shop Target for Specialty Gift Cards you will love at great low prices.
                        </desc> <!--description of the card-->
                        <websiteAddress>http://www.targer.com</websiteAddress>
                        <email>target@nhs.net</email>
                        <quantity>5</quantity>
                    </Card>
                </digital>

                <digital>
                    <Card id="a5" giftOf="sto1">
                        <name type="digital">Steam gift card</name> <!--name of the gift card-->
                        <from>Steam</from> <!--from whom the card is-->
                        <type codenumber="A1I9N">Digital</type> <!--type of card-->
                        <cost>$50.95</cost>
                        <balance>$100</balance> <!--balance of the card-->
                        <redeemCode codeOf="a5">A1I9N</redeemCode>
                        <validity cardUsability="2 year">
                            <manufactured_date>7/3/2020</manufactured_date>
                            <expiry_date>7/3/2022</expiry_date>
                        </validity>
                        <number_of_users>5</number_of_users>
                        <discount_vouchers>
                            <number_of_vouchers>1</number_of_vouchers>
                            <discounted_percentage>25%</discounted_percentage>
                        </discount_vouchers>
                        <rating maxRating="5">2</rating>
                        <desc>
                            Give the gift of more games with Steam Gift Cards.You can directly contribute to
                            by digitally sending a gift card
                        </desc>
                        <websiteAddress>http://www.steam.com</websiteAddress> <!--official website of the card company-->
                        <email>steam@nhs.net</email>
                        <quantity>2</quantity>
                        <refundable_within>1 month</refundable_within>
                    </Card>
                </digital>

                <digital>
                    <Card id="a7" giftOf="sto1">
                        <name type="digital">Spotify gift card</name> <!--name of the gift card-->
                        <from>Spotify</from> <!--from whom the card is-->
                        <type codenumber="CC9VC">Digital</type> <!--type of card-->
